type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type FirebaseProject @table {
  name: String!
  projectId: String!
  createdAt: Timestamp!
  description: String
  user: User
}

type AndroidApp @table {
  packageName: String!
  createdAt: Timestamp!
  appName: String
  firebaseProject: FirebaseProject
}

type ShaCertificate @table {
  hash: String!
  type: String!
  createdAt: Timestamp!
  androidApp: AndroidApp
}